[package]
name = "config_tools_derive"
version = "0.1.0"
edition = "2021"
authors = ["Gray Logan <literal.gray@gmail.com>"]
description = "Derive macros for config-tools."
license = "MIT"
repository = "https://github.com/piccoloser/config-tools"
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
proc-macro2 = "1.0.87"
quote = "1.0.37"
syn = { version = "2.0.79", features = ["full"] }

[dev-dependencies]
config_tools = { path = "../config_tools" }

[lib]
proc-macro = true